"""Original artwork metadata used by the drawing gallery."""

ARTWORKS = [{'id': 'lion',
  'name': 'Lion',
  'medium': 'Graphite on paper',
  'width': 1000,
  'height': 1291,
  'alt': 'A lion on a rock surrounded by forest foliage, rendered in graphite'},
 {'id': 'porsche',
  'name': 'Porsche',
  'medium': 'Graphite on paper',
  'width': 1600,
  'height': 1076,
  'alt': 'A Porsche sports car on a winding mountain road, drawn in graphite'},
 {'id': 'senna',
  'name': 'Ayrton Senna',
  'medium': 'Graphite on paper',
  'width': 1024,
  'height': 782,
  'alt': 'Graphite portrait of Ayrton Senna wearing his racing helmet'},
 {'id': 'leopard',
  'name': 'Leopard',
  'medium': 'Graphite on paper',
  'width': 750,
  'height': 1034,
  'alt': 'Detailed graphite drawing of a leopard'},
 {'id': 'tom-cruise',
  'name': 'Tom Cruise',
  'medium': 'Graphite on paper',
  'width': 765,
  'height': 1135,
  'alt': 'Graphite portrait of Tom Cruise'},
 {'id': 'coco',
  'name': 'Coco',
  'medium': 'Graphite on paper',
  'width': 685,
  'height': 883,
  'alt': 'Coco, a long-haired dog drawn in graphite by Varun Puskur'},
 {'id': 'gandhi',
  'name': 'Mahatma Gandhi',
  'medium': 'Graphite on paper',
  'width': 1555,
  'height': 2000,
  'alt': 'Graphite portrait of Mahatma Gandhi'},
 {'id': 'sreeko',
  'name': 'Sreeko',
  'medium': 'Graphite on paper',
  'width': 750,
  'height': 1118,
  'alt': 'Sreeko, an original graphite drawing by Varun Puskur'},
 {'id': 'thathamma',
  'name': 'Thathamma',
  'medium': 'Graphite on paper',
  'width': 750,
  'height': 1019,
  'alt': 'Thathamma, an original graphite portrait by Varun Puskur'},
 {'id': 'eiffel-tower',
  'name': 'Eiffel Tower',
  'medium': 'Graphite on paper',
  'width': 750,
  'height': 987,
  'alt': 'Graphite drawing of the Eiffel Tower'},
 {'id': 'lola',
  'name': 'Lola',
  'medium': 'Graphite on paper',
  'width': 750,
  'height': 1068,
  'alt': 'Lola, an original graphite drawing by Varun Puskur'},
 {'id': 'digital-1',
  'name': 'Untitled · I',
  'medium': 'Digital',
  'width': 2000,
  'height': 1500,
  'alt': 'Untitled digital artwork by Varun Puskur, first study'},
 {'id': 'digital-2',
  'name': 'Untitled · II',
  'medium': 'Digital',
  'width': 750,
  'height': 563,
  'alt': 'Untitled digital artwork by Varun Puskur, second study'},
 {'id': 'digital-6',
  'name': 'Untitled · III',
  'medium': 'Digital',
  'width': 750,
  'height': 770,
  'alt': 'Untitled digital artwork by Varun Puskur, third study'},
 {'id': 'digital-5',
  'name': 'Untitled · IV',
  'medium': 'Digital',
  'width': 750,
  'height': 563,
  'alt': 'Untitled digital artwork by Varun Puskur, fourth study'}]
