'use client';
import Link from 'next/link';
import { useState } from 'react';
import { usePathname } from 'next/navigation';
import { BrandMark } from '@/components/brand-mark';
import { ArrowUpRight, ArrowUp, Copy, Check } from 'lucide-react';
export const email = 'puskurvarun@gmail.com';
export const linkedin = 'https://www.linkedin.com/in/varunpuskur/';
export function Header(){const pathname = usePathname();return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header wrap"><Link className="wordmark" href="/" aria-label="Varun Puskur home"><BrandMark/></Link><nav aria-label="Main navigation"><Link href="/work" aria-current={pathname?.startsWith('/work') ? 'page' : undefined}>Work</Link><Link href="/#experience">Experience</Link><Link href="/art" aria-current={pathname === '/art' ? 'page' : undefined}>Art</Link><Link href="/#contact">Contact</Link></nav><Link className="header-resume" href="/resume">Résumé <ArrowUpRight size={16}/></Link></header></>}
export function Footer(){const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false); async function copy(){try{await navigator.clipboard.writeText(email);setCopied(true);setCopyError(false);setTimeout(()=>setCopied(false),2500)}catch{setCopyError(true)}}return <footer id="contact" className="footer"><div className="wrap"><div className="footer-main"><div><h2>Get in touch</h2><p className="contact-note">Open to software engineering internships<br />for Summer 2027.</p></div><div className="contact-details"><a className="email-link" href={'mailto:'+email}>{email}</a><div className="contact-actions"><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?'Email copied':'Copy email'}</span></button><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={16}/></a><a href="https://github.com/varunpuskur" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a></div><span className="copy-status" aria-live="polite">{copyError?'Please select and copy the email address above.':copied?'Copied to clipboard.':''}</span></div></div><div className="footer-bottom"><Link className="brand-home" href="/" aria-label="Varun Puskur home"><BrandMark/></Link><span>© {new Date().getFullYear()} Varun Puskur</span><a href="#main">Back to top <ArrowUp size={16}/></a></div></div></footer>}
export function PrintButton(){return <button className="button button-dark no-print" onClick={()=>window.print()}>Print / save as PDF <ArrowUpRight size={17}/></button>}
