import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { Header, Footer } from '@/components/site-shell';
import { ProjectFlow } from '@/components/project-flow';
import './encryptron.css';

export const metadata: Metadata = { title: 'Encryptron — Software Case Study', description: 'A Python and Flask learning project exploring file processing, authentication, and SQLite-backed access management.' };
const repository = 'https://github.com/varunpuskur/securefileutility';

export default function Encryptron() {
  return <><Header /><main id="main" className="wrap">
    <section className="page-hero"><Link className="back-link" href="/work#encryptron"><ArrowLeft size={16} /> Back to case studies</Link><p className="case-type">Software case study</p><h1>Encryptron</h1><p className="large-copy">A file encryption prototype, from the upload form to access checks.</p><div className="case-actions"><a href={repository} className="button button-dark" target="_blank" rel="noreferrer">View source on GitHub <ArrowUpRight size={17} /></a></div><dl className="project-facts"><div><dt>Languages</dt><dd>Python & JavaScript</dd></div><div><dt>Framework</dt><dd>Flask & Jinja</dd></div><div><dt>Database</dt><dd>SQLite</dd></div><div><dt>Scope</dt><dd>Educational prototype</dd></div></dl></section>
    <div className="case-flow"><ProjectFlow /></div>
    <div className="case-body">
      <section className="case-row"><div><h2>What I built</h2></div><div><p>I built a Flask app with account registration, encryption and decryption flows, and an interface for managing file permissions. Users select a file, enter a passphrase, and download the result with an <code>.enc</code> extension.</p><p>The frontend uses HTML, CSS, JavaScript, and Jinja templates. The backend handles sessions, compression, file transformations, and SQLite records. It is an educational prototype with a custom cipher.</p></div></section>
      <section className="case-row"><div><h2>The upload flow</h2></div><div><p>I split the interface into three steps, with JavaScript controlling which fields and instructions are visible.</p><ol className="upload-flow"><li><h3>Choose a file</h3><p>The selected filename replaces “Browse Files.” Reset clears the selection, and Next moves to the passphrase step.</p></li><li><h3>Enter a passphrase</h3><p>A password field collects the passphrase. Back returns to the file step; an empty passphrase prevents moving forward.</p></li><li><h3>Submit and download</h3><p>The final screen names the file being processed. On submission, the selected file and passphrase are copied into a multipart form and sent to Flask.</p></li></ol><a className="text-link" href={repository + '/blob/main/templates/encrypt.html'} target="_blank" rel="noreferrer">Read the frontend flow <ArrowUpRight size={15} /></a></div></section>
      <section className="case-row"><div><h2>Behind the form</h2></div><ul className="insights"><li><h3>Accounts and sessions</h3><p>Werkzeug hashes account passwords with PBKDF2-SHA256 and checks them at sign-in. Flask sessions carry the user’s ID, and protected routes redirect signed-out visitors to the login page.</p></li><li><h3>Compression and processing</h3><p>The app reads the upload into memory, compresses it with <code>zipfile</code>, and applies the custom transformation. The decryption flow reverses the transformation and decompresses the result.</p></li><li><h3>Passphrase and cipher</h3><p>The file passphrase is hashed with SHA-256, and the first 16 bytes become key material for a custom ten-round, Feistel-style transformation. It processes 16-byte blocks. This experimental routine is separate from the PBKDF2 hashing used for account passwords.</p></li><li><h3>Three database tables</h3><p><code>users</code> holds accounts and password hashes. <code>files</code> records the filename, owner, and timestamp. <code>permissions</code> connects file IDs to users with access; the owner gets a permission record when a file is processed.</p></li></ul></section>
      <section className="case-row"><div><h2>Returning the file</h2></div><div><p>The processing route wraps the result in <code>BytesIO</code> and returns it with Flask’s <code>send_file</code>. The file contents stay in memory for this request; SQLite stores the associated records.</p><pre className="implementation-code" tabIndex={0} aria-label="Python source excerpt: returning the processed file"><code>{`return send_file(
    io.BytesIO(encrypted_data),
    mimetype='application/octet-stream',
    as_attachment=True,
    download_name=encrypted_filename
)`}</code></pre><p className="implementation-caption">From the encryption route in <a href={repository + '/blob/main/app.py'} target="_blank" rel="noreferrer">app.py</a>.</p></div></section>
      <section className="case-row"><div><h2>Decryption and sharing</h2></div><div><p>Before decryption, the app looks up the uploaded filename and checks whether the signed-in user owns the record or has a matching permission entry. A missing record or failed permission check stops the request before processing.</p><p>The Manage Access page lists the owner’s files and the usernames with access. Its forms can grant access, revoke a permission, or remove a file’s database record. Granting access does not send the file itself.</p></div></section>
      <section className="case-row"><div><h2>Memory and storage</h2></div><div><p>In-memory processing keeps this workflow straightforward, but the file size directly affects memory usage. A larger deployment would need explicit limits and a different strategy for large files.</p><p>SQLite makes local setup simple. Moving to multiple application instances would require revisiting database access and deployment choices.</p></div></section>
      <section className="case-row"><div><h2>What I’d carry forward</h2></div><div><p>Building the full flow made the different responsibilities clearer: form validation, file processing, account authentication, and file permissions each need their own checks.</p><p>For the next backend project, I’d define access rules and failure cases earlier, and keep file-processing logic separate from route handlers so it can be tested independently.</p></div></section>
      <section className="case-row project-scope"><div><h2>What I’d change next</h2></div><div><p>The custom cipher is experimental, so this version is not intended to protect sensitive files. I’d replace it with vetted authenticated encryption before considering production use.</p><p>I’d also make ownership checks consistent across every permission-changing route, use an unambiguous file identifier instead of relying on filename lookup, and add upload limits. Tests should cover missing files, invalid passphrases, duplicate filenames, and unauthorized permission changes.</p><p>On the frontend, I’d replace browser alerts with inline validation and simplify the form submission so the file input does not need to be copied.</p></div></section>
      <p className="case-source"><a className="text-link" href={repository + '/blob/main/app.py'} target="_blank" rel="noreferrer">Read the implementation <ArrowUpRight size={15} /></a></p>
    </div>
  </main><Footer /></>;
}
